{{- if not .Values.config.botConfigExistingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slack-openai-bot.botConfigMapName" . }}
  labels:
    {{- include "slack-openai-bot.labels" . | nindent 4 }}
data:
  bot.config.json: |
    {{- .Values.config.botConfig | toJson | nindent 4 }}
{{- end }}

