{{- if not .Values.config.servicesExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slack-openai-bot.servicesSecretName" . }}
  labels:
    {{- include "slack-openai-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  services.json: |
    {{- .Values.config.services | toJson | nindent 4 }}
{{- end }}

